### ISSUE TITLE
diskv s.storage.ReadString undefined

### ISSUE THREAD

**Issue by devchunk** [mkabilov/pg2ch#37]
When I try
```
go get -u github.com/mkabilov/pg2ch
```

I will got:
```
# github.com/mkabilov/pg2ch/pkg/utils/kvstorage
root/go/pkg/mod/github.com/mkabilov/pg2ch@v1.0.0/pkg/utils/kvstorage/diskv.go:52:41: s.storage.ReadString undefined (type *diskv.Diskv has no field or method ReadString)
root/go/pkg/mod/github.com/mkabilov/pg2ch@v1.0.0/pkg/utils/kvstorage/diskv.go:60:18: s.storage.WriteString undefined (type *diskv.Diskv has no field or method WriteString)
```

**Comment by mkabilov** [comment]
this issue should be fixed by this https://github.com/mkabilov/pg2ch/pull/36 PR

**Comment by ghost** [comment]
Hey! I'm trying to install it in docker and I'm getting the same error. Any ETA for merging the PR?
Thanks!

**Comment by HardRock4Life** [comment]
![image](https://user-images.githubusercontent.com/21273349/134692727-7e9cb168-d81e-4358-8dcd-67fc6725ce70.png)

I still get this error...
